### ISSUE TITLE
Workflow breaks on macOS 12.3 due to python 2.7 deprecation

### ISSUE THREAD

**Issue by ivan-p92** [artemy/alfred-jetbrains-projects#1]
Hi, as of macOS 12.3, python 2.7 is not shipped by Apple by default anymore: [macos-12_3-release-notes](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes).

As a result, the workflow doesn't work anymore.

**Comment by artemy** [comment]
Thanks for the report! I was planning to rewrite it to python3 soon. 
Do you have a fresh install of the new macOS? If yes, then can you help me out a bit: is python3 is already included or it needs to be installed via xcode-tools/brew? What does `which python3` print?

**Comment by ivan-p92** [comment]
Hey Artem, thanks for the quick reply. Unfortunately I don't have a fresh install. I'm currently using python3 through homebrew (`/opt/homebrew/bin/python3`). I suspect python is not shipped by default at all now, but I'm not sure.

**Comment by artemy** [comment]
I've upgraded the workflows to use python3. Can you help me test it and report if it works with your python3 setup? You don't need to test all the versions (idea/pycharm/etc.), just the one you were using before
[alfred-jetbrains-project-python3-beta.zip](https://github.com/artemy/alfred-jetbrains-projects/files/8289429/alfred-jetbrains-project-python3-beta.zip)

**Comment by ivan-p92** [comment]
Awesome! I tested the idea workflow and it works flawlessly with my setup 😊 
Thanks!

**Comment by trietsch** [comment]
Works here as well, haven't upgraded to macOS 12.3 yet.

**Comment by artemy** [comment]
thanks everyone, you can enjoy [v2.0 release](https://github.com/artemy/alfred-jetbrains-projects/releases/tag/v2.0) with python3 support
