### ISSUE TITLE
Recommendation: Use /usr/bin/python3

### ISSUE THREAD

**Issue by vitorgalvao** [artemy/alfred-jetbrains-projects#19]
I recommend you use `/usr/bin/python3` instead of `python3` because that’ll guarantee a more consistent version for users. Sometimes Python makes some weird breaking change that users suddenly update to from Homebrew which can lead to inconsistent behaviour. So you’d do something like (already taking #20 into account):

```bash
/usr/bin/python3 recent_projects.py androidstudio "${1}"
```

That is unlikely to be an issue for this particular workflow, but still it’s best to not have to worry about it.

**Comment by artemy** [comment]
Fixed in #23
