### ISSUE TITLE
Always use `with input as argv`

### ISSUE THREAD

**Issue by vitorgalvao** [artemy/alfred-jetbrains-projects#20]
[Always prefer `with input as argv` over `with input as {query}`](https://www.alfredforum.com/topic/19924-prefer-with-input-as-argv-for-running-scripts/), there’s a reason it’s the default. So you’d do something like (already taking #19 into account):

```bash
/usr/bin/python3 recent_projects.py androidstudio "${1}"
```

I’d submit the fix as a PR, but there’s no info.plist in the repo.

I’d also recommend quoting your variables. I.e. in the Run Script: `open -nb "${bundle_id}" --args "${@}"`

**Comment by artemy** [comment]
Fixed in #23
