### ISSUE TITLE
There should be no `v` in the version

### ISSUE THREAD

**Issue by vitorgalvao** [artemy/alfred-jetbrains-projects#21]
Versions should be numeric and use periods, the `v` should not be added. See how it looks in the editor:

<img width="351" alt="image" src="https://github.com/user-attachments/assets/2a7df7d7-8cfd-46d2-97b8-549c9c2e6554">

I’d submit the fix as a PR, but there’s no info.plist in the repo.

**Comment by artemy** [comment]
Fixed in #23
