### ISSUE TITLE
Projects don't open with Toolbox version 2.0.x

### ISSUE THREAD

**Issue by martinvisser** [artemy/alfred-jetbrains-projects#9]
After a recent upgrade of the JetBrains Toolbox to 2.0.x it seems the name of Intelij changed to `IntelliJ IDEA Ultimate.app`, but the script refers to `IntelliJ IDEA.app`.

**Comment by artemy** [comment]
I've released v2.2 that should fix this issue https://github.com/artemy/alfred-jetbrains-projects/releases/tag/v2.2

**Comment by martinvisser** [comment]
Thanks @artemy, works perfectly!
